### ISSUE TITLE
NoMethodError (undefined method `force_encoding' for nil:NilClass)

### ISSUE THREAD

**Issue by uzaif313** [renuo/rails_api_logger#1]
@coorasse  i try out this Gem via console for calling sample open json api but while calling   `log = OutboundRequestLog.from_request(request)` its give me an error

```ruby
  uri = URI("http://jsonplaceholder.typicode.com/users/")
  http = Net::HTTP.start(uri.host, uri.port)
  request = Net::HTTP::Get.new(uri)
  log = OutboundRequestLog.from_request(request)
  response = http.request(request)
  log.response_body = response.body
  log.response_code = response.code
  log.save!
```

```ruby
NoMethodError: undefined method `force_encoding' for nil:NilClass
from /home/hp/.rvm/gems/ruby-2.5.0@dummt-api/gems/rails_api_logger-0.2.5/lib/rails_api_logger/request_log.rb:15:in `from_request'
````

**Comment by uzaif313** [comment]
@coorasse  after digging into code i found out that i need to pass empty request.body and now its working. Thanks guys Gem.

**Comment by uzaif313** [comment]
@coorasse is there any option through which we can store headers of request or response.

**Comment by coorasse** [comment]
Thanks for the issue. I released version 0.2.6 where you can log even if the body is not present so you don't need to do `request.body = {}.to_json` anymore.

**Comment by coorasse** [comment]
Regarding the headers no, not at the moment, but I will gladly work on it. 👍 I think is a good idea!

**Comment by uzaif313** [comment]
@coorasse  i did modify `RequestLog`  class to enable storing headers. Thanks for awesome gem
