### ISSUE TITLE
Log request and response headers

### ISSUE THREAD

**Issue by coorasse** [renuo/rails_api_logger#2]
This is a feature request. Give the possibility to log both request and response headers.

**Comment by uzaif313** [comment]
@coorasse  i did overwrite `RequestLog` class to implement request header storing stuff

**Comment by coorasse** [comment]
maybe you want to share your code or open a PR? it would be really appreciated! 🙇

**Comment by uzaif313** [comment]
@coorasse  I will create PR

**Comment by abuisman** [comment]
@uzaif313 That would be great!

**Comment by uzaif313** [comment]
@abuisman  I will create PR this weekend

**Comment by abuisman** [comment]
@uzaif313 can’t wait! Thanks

**Comment by panozzaj** [comment]
Here is the PR @uzaif313 created: https://github.com/renuo/rails_api_logger/pull/3

**Comment by jadelekekpmg** [comment]
Any update on this? Is the PR merged?

**Comment by Juleffel** [comment]
In case anyone needs this, I merged all forks of this repo in another [new fork](https://github.com/Juleffel/rails_api_logger) 🙃 This include adding `uuid`, `request_headers` and `used_ip` to the logs.
