### ISSUE TITLE
Handle API inflections

### ISSUE THREAD

**Issue by jaykilleen** [renuo/rails_api_logger#4]
Giving this gem a go. Upon first install I hit a snag caused by my `inflections.rb` configuration. Now, this is an easy fix on my end but I thought I would give some feedback and up to you if you choose to address it :) Looking forward to replacing my logger file for a table.

```ruby
ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.acronym 'API'
end
```

This configuration then causes migration templates to throw the error:

```bash
NameError: uninitialized constant CreateRailsAPILoggerTable
Did you mean?  CreateRailsApiLoggerTable
```

**Comment by coorasse** [comment]
I believe we won't address this in code. Having this issue as a reference should be enough if somebody faces the same problem.  Thanks! 🙏
